### ISSUE TITLE
Apply including /src/test/ files

### ISSUE THREAD

**Issue by javierferrer** [walkmod/maven-walkmod-plugin#8]
First of all, thanks for all your valuable work here.
When I run `mvn org.walkmod.maven.plugins:walkmod-maven-plugin:apply`, all files under /src/main/ are analyzed, but I also wish to analyze the files under /src/test/
Is this possible using Maven arguments? I tried -Dpath but it did not work at all.

**Comment by rajkrm** [comment]
Hi Javier

Have you encountered the below error when running walkmod apply.

ERROR [main] - Invalid configuration
org.walkmod.conf.ConfigurationException: Ivy can not resolve the artifacts. Cause: unresolved dependency: org.walkmod#walkmod-imports-cleaner-plugin;latest.integration: not found;unresolved dependency: org.walkmod#walkmod-maven-plugin;latest.integration: not found;unresolved dependency: org.walkmod#walkmod-javalang-plugin;latest.integration: not found;unresolved dependency: org.walkmod#walkmod-javalang-plugin;[2.0, 4.0): not found
at org.walkmod.conf.providers.IvyConfigurationProvider.resolveArtifacts(IvyConfigurationProvider.java:233)
at org.walkmod.conf.providers.IvyConfigurationProvider.load(IvyConfigurationProvider.java:156)
at org.walkmod.conf.ConfigurationManager.executeConfigurationProviders(ConfigurationManager.java:124)
at org.walkmod.conf.ConfigurationManager.addProviders(ConfigurationManager.java:61)
at org.walkmod.conf.ConfigurationManager.<init>(ConfigurationManager.java:75)
at org.walkmod.conf.ConfigurationManager.<init>(ConfigurationManager.java:79)
at org.walkmod.WalkModFacade.readConfig(WalkModFacade.java:181)
at org.walkmod.WalkModFacade.run(WalkModFacade.java:256)
at org.walkmod.WalkModFacade.apply(WalkModFacade.java:142)
at org.walkmod.commands.ApplyCommand.execute(ApplyCommand.java:40)
at org.walkmod.WalkModDispatcher.execute(WalkModDispatcher.java:172)
at org.walkmod.WalkModDispatcher.main(WalkModDispatcher.java:197)
ERROR [main] - Invalid configuration
java.lang.NullPointerException
at org.walkmod.WalkModFacade.run(WalkModFacade.java:264)
at org.walkmod.WalkModFacade.apply(WalkModFacade.java:142)
at org.walkmod.commands.ApplyCommand.execute(ApplyCommand.java:40)
at org.walkmod.WalkModDispatcher.execute(WalkModDispatcher.java:172)
at org.walkmod.WalkModDispatcher.main(WalkModDispatcher.java:197)
Exception in thread "main" java.lang.NullPointerException
at org.walkmod.WalkModFacade.run(WalkModFacade.java:284)
at org.walkmod.WalkModFacade.apply(WalkModFacade.java:142)
at org.walkmod.commands.ApplyCommand.execute(ApplyCommand.java:40)
at org.walkmod.WalkModDispatcher.execute(WalkModDispatcher.java:172)
at org.walkmod.WalkModDispatcher.main(WalkModDispatcher.java:197)
